name: BlueFusionCustomMessages
version: 1.0.1-SNAPSHOT
main: com.dreamfirestudios.bluefusioncustommessages.BlueFusionCustomMessages
api-version: 1.21
depend: [DreamCore, DreamConfig, DreamCommand, ProtocolLib, LuckPerms, PlaceholderAPI]
